# copied from ARIAC tutorials page

robot_cameras:
  floor_robot_camera:
    active: false
    type: rgb

  ceiling_robot_camera:
    active: false
    type: rgbd

static_sensors:
  conveyor_breakbeam:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.36, 3.5, 0.88]
      rpy: [0, 0, pi]